# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import munin.mot


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default=munin.mot.mot, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=munin.mot.mot, max_length=50, null=True)),
                ('argent', models.CharField(default='0', max_length=50)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(default='0', max_length=50)),
                ('puissance', models.CharField(default='0', max_length=50)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munin.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(null=True)),
                ('puissance', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='joueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munin.Joueur'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munin.TypeAgent'),
        ),
    ]
