# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bob', models.CharField(max_length=10)),
            ],
        ),
    ]
