# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='puissance',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
