# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0002_caca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='argent',
        ),
    ]
