# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0002_agent_puissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordre',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='prix',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ordre',
        ),
    ]
