# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0003_auto_20180619_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(null=True)),
                ('puissance', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='puissance',
        ),
    ]
