# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0003_remove_joueur_argent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caca',
        ),
        migrations.AddField(
            model_name='joueur',
            name='argent',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
