# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('munin', '0004_auto_20180621_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munin.TypeAgent'),
        ),
    ]
