# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0004_auto_20180702_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeagent',
            name='prix_achat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
