# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0005_auto_20180621_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(max_length=50)),
                ('puissance', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munin.Agent')),
            ],
        ),
    ]
